name: Generate Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Weekly

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://ai.pinoyseoul.com/
      - name: Commit and push sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: Auto-generate sitemap.xml"
          git push
